version: "3.7"
services:
  vault:
    image: vault:1.10.0
    container_name: vault
    hostname: vault
    ports:
      - 127.0.0.1:8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./vault/file:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: unless-stopped

  vault-init:
    image: vault:1.10.0
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://vault:8200
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - ./vault/file:/vault/file/
      - ./vault/_key-token:/vault/_key-token/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault